// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	comment "api-airbnb-alta/features/comment"

	mock "github.com/stretchr/testify/mock"
)

// CommentRepo is an autogenerated mock type for the RepositoryInterface type
type CommentRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *CommentRepo) Create(input comment.Core) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(comment.Core) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *CommentRepo) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *CommentRepo) GetAll() ([]comment.Core, error) {
	ret := _m.Called()

	var r0 []comment.Core
	if rf, ok := ret.Get(0).(func() []comment.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]comment.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *CommentRepo) GetById(id int) (comment.Core, error) {
	ret := _m.Called(id)

	var r0 comment.Core
	if rf, ok := ret.Get(0).(func(int) comment.Core); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(comment.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: input, id
func (_m *CommentRepo) Update(input comment.Core, id int) error {
	ret := _m.Called(input, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(comment.Core, int) error); ok {
		r0 = rf(input, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCommentRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommentRepo creates a new instance of CommentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommentRepo(t mockConstructorTestingTNewCommentRepo) *CommentRepo {
	mock := &CommentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
